# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efc423003c049a268a1da7961c80a6b2d5850af571e3317d27649fa9deef32eb740b4784b388df1aed47178628f541844cbc9d21facddc030a0b1ebc5edc1721

test:
  secret_key_base: fcc0abf0f3a3a4f81cd0d8d780a18aa7226e23a3afa7c1cdd3023fb3c777d65c9a6e202e12b126668dec49800f1f5b268cbdbcca9e54706989e045b5fef625b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
